### ISSUE TITLE
Adjust projection

### ISSUE THREAD

**Issue by michieldewilde** [oSoc15/leiedal-plong#4]
The current projection system makes the map shift.
Estimated time: No estimation, unsure how bug will be fixed.

**Comment by Dobbelsteen** [comment]
Either the map is unshifted and the projection is wrong, or the map is shifted and the projection is semi-correct.
No fix in sight for now, sadly.

**Comment by Dobbelsteen** [comment]
For now there are 2 options:
- Use CRS: map tiles are shifted, but projection is fairly accurate
- Disable CRS: map tiles are correct, but projection is very shifted.

In the current master I used CRS (see [resources/views/map.blade.php](https://github.com/oSoc15/leiedal-plong/blob/master/resources/views/map.blade.php#L115-L145))
